machine:
  python:
    version: 2.7.13
  post:
    - pyenv global 2.7.13

dependencies:
  pre:
    - pip -q install --upgrade pip
    - pip -q install PyYAML mkdocs pyembed-markdown

test:
  pre:
    - make docs
